spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://192.168.0.119/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#server:
#  port: 8081